Reinstate PaymentsLearner report
SkillsFundingAgency/das-identify-data-locks pull request #50
Opened 2020-09-18 14:20 UTC by benagain

2020-09-18 15:43 UTC, DevenKShah requested changes
Looks good, the only change is the missing page authorization.

2020-09-18 15:43 UTC, DevenKShah commented on src/SFA.DAS.IdentifyDataLocks.Web/Pages/PaymentsLearner.cshtml.cs
> +        public string Uln { get; set; } = "9000000407";
Do we need this hard coded value?

2020-09-18 15:43 UTC, DevenKShah commented on src/SFA.DAS.IdentifyDataLocks.Web/Pages/PaymentsLearner.cshtml.cs
> +            //var a = Bob(learnerUln);
Commented code can be removed?

2020-09-18 15:43 UTC, DevenKShah commented on src/SFA.DAS.IdentifyDataLocks.Web/Pages/PaymentsLearner.cshtml.cs
> +                .SelectMany(x => x/*.OrderByDescending(y => y.IlrSubmissionDateTime)*/.Take(1))
Commented code

2020-09-18 15:43 UTC, DevenKShah commented on src/SFA.DAS.IdentifyDataLocks.Web/Pages/PaymentsLearner.cshtml.cs
> +                //.Where(x => x.PriceEpisodeIdentifier)
Commented code

2020-09-18 15:43 UTC, DevenKShah commented on src/SFA.DAS.IdentifyDataLocks.Web/Pages/PaymentsLearner.cshtml.cs
> +                .Where(x => x.LearnerUln == learnerUln);//.ToList();
Commented code

2020-09-18 15:43 UTC, DevenKShah commented on src/SFA.DAS.IdentifyDataLocks.Web/Pages/PaymentsLearner.cshtml.cs
> +    public class PaymentsLearnerModel : PageModel
The model is quiet busy, I appreciate that this is for internal support.

2020-09-18 15:43 UTC, DevenKShah commented on src/SFA.DAS.IdentifyDataLocks.Web/Pages/PaymentsLearner.cshtml.cs
> +    public class PaymentsLearnerModel : PageModel
You need to add authorization for this page.

2020-09-21 07:34 UTC, benagain commented
> 
> 
> Looks good, the only change is the missing page authorization.

Yes!  Thank you for spotting that.

2020-09-21 09:33 UTC, DevenKShah approved these changes

2020-09-21 10:03 UTC, merged